name: Monitoring - E2E

on:
  workflow_dispatch:

jobs:
  dev:
    name: Run test
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: main
            path: learning-repo

        - name: LS -L for outer repo
          run: |
            pwd
            echo github.workspace=${{ github.workspace }}
            ls -l
            find
            echo secrets.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          shell: bash

        - name: Checkout HomeExpenses - public repo
          uses: actions/checkout@v3
          with:
            repository: home-expenses-github-username/home-expenses
            path: my-he-repo
            ref: main

        - name: Checkout scroll-app - public repo
          uses: actions/checkout@v3
          with:
            repository: unlimit1984/scroll-app
            path: my-scroll-app
#            ref: master

        - name: Checkout private-repo
          uses: actions/checkout@v3
          with:
            repository: unlimit1984/private-repo
            path: my-private-repo
            ref: main
#            token: ${{ secrets.GITHUB_TOKEN }}

        - name: LS -L for second repo
          run: |
            pwd
            echo github.workspace=${{ github.workspace }}
            ls -l
            find
          shell: bash
